Create strings_ar.i18n.json
adil192/saber pull request #468
Opened 2023-03-13 16:50 UTC by muhammadbahaa2001

Arabic Translation for Saber.

2023-03-13 17:04 UTC, adil192 requested changes
There seem to be a few formatting errors with incorrect escape sequences scattered around the file. Please fix these and I'll take another look :)

2023-03-13 21:07 UTC, muhammadbahaa2001 commented
Sorry,  what do you mean exactly by "few formatting errors with incorrect escape sequences scattered around the file"? give an example from what I did, so I can fix it.

2023-03-14 00:25 UTC, adil192 requested changes
Also please can you correct the spelling of "Sabre" to "Saber"

Edit: This was done a few times @muhammadbahaa2001

2023-03-14 06:14 UTC, adil192 requested changes

2023-03-14 06:14 UTC, adil192 commented on lib/i18n/strings_ar.i18n.json
> +    "systemLanguage": "System language",
Looks like you forgot this line!

2023-03-14 21:32 UTC, muhammadbahaa2001 commented
> Also please can you correct the spelling of "Sabre" to "Saber"
> 
> Edit: This was done a few times @muhammadbahaa2001

Sorry for my mistakes (For every "Sabre" I miss it)

2023-03-15 06:07 UTC, adil192 commented
> Sorry for my mistakes (For every "Sabre" I miss it), I wish everything is corrected now.

No worries!

2023-03-15 06:08 UTC, adil192 approved these changes
LGTM, thanks for your contribution!

2023-03-15 06:15 UTC, adil192 commented
Would you be interested in being mentioned when there's new strings that need to be translated? https://github.com/adil192/saber/issues/19#issuecomment-1306096416

2023-03-15 06:25 UTC, merged

2023-03-15 11:51 UTC, muhammadbahaa2001 commented
> Would you be interested in being mentioned when there's new strings that need to be translated? [#19 (comment)](https://github.com/adil192/saber/issues/19#issuecomment-1306096416)

Of course, why not?

2023-03-15 11:52 UTC, muhammadbahaa2001 commented
> LGTM, thanks for your contribution!

You are welcome bro :)