feat: delete and duplicate selection
adil192/saber pull request #937
Opened 2023-09-29 20:39 UTC by AraxTheCoder

This adds the ability to delete and duplicate the selection as requested in #170.
These two new options get shown in the toolOptions collapsible menu, as seen in the screenshot.

![Screenshot_2023-09-29-22-30-41-118_com adilhanney saber](https://github.com/adil192/saber/assets/40892690/991021c1-b615-48a5-945c-724a5e9aafde)

I still need to copy the "Delete" from imageOptions of all languages to selectionOptions, but when I tried it so far, other translations got replaced with the missing English translation.
Any help on how I can do this correctly is welcome.

2023-09-30 14:13 UTC, adil192 requested changes

2023-09-30 14:13 UTC, adil192 commented on lib/components/toolbar/toolbar.dart
> +                    }
Please can you make this a conditional operator:
```dart
toolOptionsType.value = toolOptionsType.value == ToolOptions.select
    ? ToolOptions.hide
    : ToolOptions.select;
```

2023-09-30 14:13 UTC, adil192 commented on lib/components/toolbar/toolbar.dart
> +                    // Default showing selection functions
```suggestion
                    // Show the selection bar by default
```

2023-09-30 14:13 UTC, adil192 commented on lib/pages/editor/editor.dart
> +              if(select.doneSelecting){
Prefer early returns in situations like this
```dart
if (select.doneSelecting) return;
```

2023-09-30 14:18 UTC, adil192 commented
> I still need to copy the "Delete" from imageOptions of all languages to selectionOptions, but when I tried it so far, other translations got replaced with the missing English translation. Any help on how I can do this correctly is welcome.

I typically do this as a separate commit/PR to keep the diff readable.
That being said, were you using a command like
```bash
dart run slang edit copy path.to.imageOptions.delete path.to.selectionOptions.delete
```

2023-09-30 14:18 UTC, adil192 commented on lib/i18n/strings.i18n.yaml
> +  selectionOptions:
Please can you also change this to `selectionBar:`

2023-09-30 14:56 UTC, AraxTheCoder commented
> > I still need to copy the "Delete" from imageOptions of all languages to selectionOptions, but when I tried it so far, other translations got replaced with the missing English translation. Any help on how I can do this correctly is welcome.
> 
> I typically do this as a separate commit/PR to keep the diff readable. That being said, were you using a command like
> 
> ```shell
> dart run slang edit copy path.to.imageOptions.delete path.to.selectionOptions.delete
> ```

Ok so you take care of this yourself?

2023-10-04 08:57 UTC, adil192 approved these changes

2023-10-04 08:58 UTC, merged

2023-10-04 08:58 UTC, adil192 commented
Thank you!